version: "3.8"

services:
  metaverse-http:
    image: gauravbpit1998922/metaverse-http:latest
    container_name: metaverse-http
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./apps/http/.env
  metaverse-ws:
    image: gauravbpit1998922/metaverse-ws:latest
    container_name: metaverse-ws
    ports:
      - "3001:3001"
    restart: always
    env_file:
      - ./apps/ws/.env
  metaverse-frontend:
    image: gauravbpit1998922/metaverse-frontend:latest
    container_name: metaverse-frontend
    restart: always
    depends_on:
      - metaverse-http
      - metaverse-ws
    ports:
      - "5173:5173"
    env_file:
      - ./apps/metaverse-frontend/.env
