name: Build on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install Dependencies
        run: cd metaverse && npm install

      - name: Run lint Checking
        run: cd metaverse && npm run lint

      - name: Run Build
        run: cd metaverse && npm run build
